package com.example.myfirstcafe.core.ui.strings

object AppStrings {
    const val SPLASH = "Splash Image"
    const val RECEIPTS = "Receipts"
    const val NO_RECEIPT_MESSAGE = "You don’t have any receipt yet"
    const val DELETE_RECEIPT = "Delete receipt"
    const val CONFIRM_DELETE_RECEIPT = "Do you want to delete this receipt?"
    const val YES = "Yes"
    const val NO = "No"
    const val ADD = "Add"
    const val BACK = "Back"
    const val ADD_RECEIPT = "Add receipt"
    const val NEXT = "Next"
    const val NO_ITEM_SELECTED_MESSAGE = "You don’t have any item selected yet"
    const val PLUS = "Plus"
    const val MINUS = "Minus"
    const val RECEIPTS_DETAILS = "Receipt details"
    const val TIP = "Tip"
    const val TIP_LABEL = "Tip (€)"
    const val SUBTOTAL = "Subtotal"
    const val VAT = "VAT (20%)"
    const val TOTAL = "Total"
    const val CHARGING = "Charging..."
    const val CHARGE_RECEIPT = "Charge receipt"
    const val PRICE_LIST = "Price list"
    const val SEARCH = "Search"
    const val SEARCH_PLACEHOLDER = "Enter here..."
    const val SEARCH_RESULTS = "Search results"
    const val NO_ITEMS_FOUND = "No items found"
    const val DELETE_ITEM_TITLE = "Delete item"
    const val DELETE_ITEM_MESSAGE = "Do you want to delete this item?"
    const val ADD_NEW_ITEM = "Add new item"
    const val EDIT_ITEM = "Edit item"
    const val ITEM_NAME = "Item name"
    const val CATEGORY = "Category"
    const val PRICE = "Price (€)"
    const val SAVE_ITEM = "Save item"
    const val VALIDATION_ALL_FIELDS = "You didn’t set all fields"
    const val PRICE_EUR = "%.2f €"

}